# Generated by Django 4.2.16 on 2024-09-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(),
        ),
    ]
