# Generated by Django 4.2.16 on 2024-09-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostapp', '0006_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
