# Generated by Django 4.2.16 on 2024-09-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostapp', '0007_billing_stripe_payment_intent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
